require('config.launch')
require('config.options')
require('config.keymaps')
require('config.autocmds')

spec('plugins.lsp.cmp')
spec('plugins.lsp.lspconfig')
spec('plugins.lsp.mason')
spec('plugins.lsp.schemastore')

spec('plugins.formatters.conform')

spec('plugins.comment')
spec('plugins.harpoon')
spec('plugins.telescope')
spec('plugins.treesitter')
spec('plugins.whichkey')

-- spec('plugins.ui.top.breadcrumbs')
spec('plugins.colorscheme')
spec('plugins.ui.alpha')
spec('plugins.ui.bottom.lualine')
spec('plugins.ui.devicons')
spec('plugins.ui.illuminate')
spec('plugins.ui.oil')
-- spec('plugins.ui.tabs.tabby')
-- spec('plugins.ui.top.navic')
spec('plugins.ui.tree.neotree')
spec('plugins.ui.ufo')

spec('plugins.aerial')
spec('plugins.autopairs')
spec('plugins.codesnap')
spec('plugins.colorizer')
spec('plugins.csv')
spec('plugins.dap')
spec('plugins.dbee')
spec('plugins.diffview')
spec('plugins.dressing')
-- spec('plugins.edgy')
spec('plugins.fidget')
-- spec('plugins.flash')
spec('plugins.gh')
spec('plugins.gitlinker')
spec('plugins.gitsigns')
-- spec('plugins.go')
-- spec('plugins.hurl')
spec('plugins.indentline')
spec('plugins.markview')
spec('plugins.mini-indetoscope')
spec('plugins.noice')
spec('plugins.nopain')
-- spec('plugins.notify')
spec('plugins.nvim-ansible-vault')
spec('plugins.nvim-surround')
spec('plugins.obsidian')
spec('plugins.octo')
spec('plugins.otter')
-- spec('plugins.overseer')
-- spec('plugins.persistence')
spec('plugins.project')
spec('plugins.bqf')
spec('plugins.resession')
-- spec('plugins.rest')
spec('plugins.scope')
spec('plugins.scrollbar')
spec('plugins.stickybuf')
spec('plugins.tabby')
spec('plugins.timber')
spec('plugins.triforce')
spec('plugins.todo')
spec('plugins.typescript-tools')

require('config.lazy')
