require('config.launch')
require('config.options')
require('config.keymaps')
require('config.autocmds')

spec('plugins.treesitter')

spec('plugins.lsp.cmp')
spec('plugins.lsp.lspconfig')
spec('plugins.lsp.mason')
spec('plugins.lsp.schemastore')
-- spec('plugins.lsp.typescript-tools')

spec('plugins.formatters.conform')

spec('plugins.telescope')
spec('plugins.comment')
spec('plugins.whichkey')
spec('plugins.harpoon')

spec('plugins.colorscheme')
spec('plugins.ui.bottom.lualine')
spec('plugins.ui.devicons')
spec('plugins.ui.oil')
spec('plugins.ui.tabs.tabby')
spec('plugins.ui.top.breadcrumbs')
spec('plugins.ui.top.navic')
spec('plugins.ui.tree.neotree')
spec('plugins.ui.illuminate')
spec('plugins.ui.ufo')
spec('plugins.ui.alpha')
spec('plugins.autopairs')
spec('plugins.gitsigns')
spec('plugins.indentline')
spec('plugins.mini-indetoscope')
spec('plugins.fidget')
spec('plugins.project')
spec('plugins.scrollbar')
spec('plugins.flash')
spec('plugins.noice')
spec('plugins.diffview')
spec('plugins.notify')
spec('plugins.todo')
spec('plugins.persistence')
spec('plugins.codeium')
spec('plugins.dap')
spec('plugins.octo')

spec('plugins.dressing')
spec('plugins.colorizer')
spec('plugins.otter')
spec('plugins.nopain')
spec('plugins.hurl')
spec('plugins.csv')
spec('plugins.typescript-tools')
require('config.lazy')
