window:
  #startup_mode: Maximized #Fullscreen
  # decorations: none

  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

  title: Alacritty

  #startup_mode: Maximized

  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 2
    y: 2

  dimensions:
    columns: 80
    lines: 24

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.9

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

scrolling:
  # Specifying '0' will disable scrolling.
  history: 1000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

font:
  normal:
    family: CaskaydiaCove Nerd Font
    style: Regular
  bold:
    family: CaskaydiaCove Nerd Font
    style: Bold
  italic:
    family: CaskaydiaCove Nerd Font
    style: Italic
  size: 18.0

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false
# Base16 Default Dark 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: "#282828"
    # soft contrast: background = '#32302f'
    foreground: "#ebdbb2"

  # Normal colors
  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  # Bright colors
  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

bell:
  animation: Ease
  duration: 1
  color: "#ffffff"

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
# Allow terminal applications to change Alacritty’s window title.
#window.dynamic_title: true
cursor:
  style:
    shape: Block
  unfocused_hollow: true
# Live config reload (changes require restart)
live_config_reload: true

# Map the keys (British keyboard layout)
key_bindings:
  - { key: Key0, mods: Alt, chars: "º" }
  - { key: Key1, mods: Alt, chars: "¡" }
  - { key: Key2, mods: Alt, chars: "€" }
  - { key: Key3, mods: Alt, chars: "#" }
  - { key: Key4, mods: Alt, chars: "¢" }
  - { key: Key5, mods: Alt, chars: "∞" }
  - { key: Key6, mods: Alt, chars: "§" }
  - { key: Key7, mods: Alt, chars: "¶" }
  - { key: Key8, mods: Alt, chars: "•" }
  - { key: Key9, mods: Alt, chars: "ª" }
